import type { SecurityReport } from "@/types/report"

export const mockReports: SecurityReport[] = [
  {
    idsummary: "sum_001",
    status: "success",
    domain_name: "globaltechcorp.com",
    risk_score: 74,
    creation_date: "2024-03-10T09:15:00Z",
    last_edit: "2024-03-10T09:22:00Z",
    summary_text:
      "Il dominio globaltechcorp.com presenta un rischio complessivo ALTO. Sono stati rilevati 2 servizi criticamente esposti su porte non standard, una significativa fuga di credenziali e una configurazione email vulnerabile allo spoofing per assenza di policy DMARC. Le vulnerabilità attive includono 3 CVE critiche non patchate. Si raccomanda intervento immediato.",
    summary_text_en:
      "The domain globaltechcorp.com presents an overall HIGH risk. 2 critically exposed services on non-standard ports were detected, significant credential leakage, and email configuration vulnerable to spoofing due to missing DMARC policy. Active vulnerabilities include 3 unpatched critical CVEs. Immediate action is recommended.",
    servizi_esposti_score: 78,
    dataleak_score: 82,
    rapporto_leak_email_score: 65,
    spoofing_score: 90,
    open_ports_score: 70,
    blacklist_score: 25,
    vulnerability_score_active: 88,
    vulnerability_score_passive: 55,
    certificate_score: 40,
    n_port: { "80": { n: 6 }, "443": { n: 9 }, "22": { n: 3 }, "8080": { n: 2 }, "3306": { n: 1 }, "5432": { n: 1 } },
    n_cert_attivi: 4,
    n_cert_scaduti: 2,
    n_asset: 18,
    n_similar_domains: 12,
    email_security: {
      spoofable: "Spoofing possible.",
      dmarc_policy: "none",
      blacklist_detections: 3,
      blacklist_total_list: 60,
      blacklist_detected_list: ["spamhaus", "surbl", "uribl"],
    },
    n_dataleak: {
      total:      { vip: 0, domain_stealer: 5, potential_stealer: 320, other_stealer: 28, general_leak: 42 },
      resolved:   { vip: 0, domain_stealer: 1, potential_stealer: 80,  other_stealer: 5,  general_leak: 10 },
      unresolved: { vip: 0, domain_stealer: 4, potential_stealer: 240, other_stealer: 23, general_leak: 32 },
      enumeration: 7,
    },
    n_vulns: {
      total:   { critical: 3, high: 15, medium: 31, low: 34, info: 0 },
      active:  { critical: 3, high: 11, medium: 22, low: 34, info: 0 },
      passive: { critical: 0, high: 4,  medium: 9,  low: 15, info: 0 },
    },
    waf: { count: 2, assets: ["www.globaltechcorp.com", "app.globaltechcorp.com"] },
    cdn: { count: 2, assets: ["static.globaltechcorp.com", "cdn.globaltechcorp.com"] },
    unique_ipv4: 8,
    unique_ipv6: 3,
  },
  {
    idsummary: "sum_002",
    status: "success",
    domain_name: "mediahub.io",
    risk_score: 43,
    creation_date: "2024-03-08T14:30:00Z",
    last_edit: "2024-03-08T14:38:00Z",
    summary_text:
      "Il dominio mediahub.io mostra un livello di rischio MEDIO. La configurazione email è parzialmente protetta. Sono stati rilevati alcuni data leak. Non sono presenti vulnerabilità critiche attive ma si segnalano diverse di gravità media. I certificati SSL risultano tutti validi.",
    summary_text_en:
      "The domain mediahub.io shows a MEDIUM risk level. Email configuration is partially protected. Some data leaks were detected. No critical active vulnerabilities present but several medium severity issues noted. All SSL certificates are valid.",
    servizi_esposti_score: 45,
    dataleak_score: 55,
    rapporto_leak_email_score: 30,
    spoofing_score: 50,
    open_ports_score: 40,
    blacklist_score: 10,
    vulnerability_score_active: 48,
    vulnerability_score_passive: 35,
    certificate_score: 15,
    n_port: { "80": { n: 3 }, "443": { n: 5 }, "22": { n: 1 }, "8443": { n: 1 } },
    n_cert_attivi: 6,
    n_cert_scaduti: 0,
    n_asset: 9,
    n_similar_domains: 5,
    email_security: {
      spoofable: "Spoofing possible.",
      dmarc_policy: "quarantine",
      blacklist_detections: 1,
      blacklist_total_list: 60,
      blacklist_detected_list: ["spamhaus"],
    },
    n_dataleak: {
      total:      { vip: 0, domain_stealer: 2, potential_stealer: 180, other_stealer: 14, general_leak: 0 },
      resolved:   { vip: 0, domain_stealer: 2, potential_stealer: 60,  other_stealer: 6,  general_leak: 0 },
      unresolved: { vip: 0, domain_stealer: 0, potential_stealer: 120, other_stealer: 8,  general_leak: 0 },
      enumeration: 3,
    },
    n_vulns: {
      total:   { critical: 0, high: 4, medium: 21, low: 40, info: 0 },
      active:  { critical: 0, high: 3, medium: 14, low: 28, info: 0 },
      passive: { critical: 0, high: 1, medium: 7,  low: 12, info: 0 },
    },
    waf: { count: 0, assets: [] },
    cdn: { count: 1, assets: ["media.mediahub.io"] },
    unique_ipv4: 4,
    unique_ipv6: 1,
  },
  {
    idsummary: "sum_003",
    status: "success",
    domain_name: "securefinance.eu",
    risk_score: 18,
    creation_date: "2024-03-05T11:00:00Z",
    last_edit: "2024-03-05T11:08:00Z",
    summary_text:
      "Il dominio securefinance.eu presenta un livello di rischio BASSO. La configurazione di sicurezza è nel complesso buona: DMARC impostato su reject. Nessuna vulnerabilità critica rilevata. I certificati SSL sono tutti validi e aggiornati.",
    summary_text_en:
      "The domain securefinance.eu presents a LOW risk level. The security configuration is overall good: DMARC set to reject. No critical vulnerabilities detected. All SSL certificates are valid and up-to-date.",
    servizi_esposti_score: 20,
    dataleak_score: 22,
    rapporto_leak_email_score: 10,
    spoofing_score: 5,
    open_ports_score: 18,
    blacklist_score: 0,
    vulnerability_score_active: 15,
    vulnerability_score_passive: 12,
    certificate_score: 8,
    n_port: { "443": { n: 4 }, "80": { n: 2 } },
    n_cert_attivi: 5,
    n_cert_scaduti: 0,
    n_asset: 6,
    n_similar_domains: 2,
    email_security: {
      spoofable: "",
      dmarc_policy: "reject",
      blacklist_detections: 0,
      blacklist_total_list: 60,
      blacklist_detected_list: [],
    },
    n_dataleak: {
      total:      { vip: 0, domain_stealer: 0, potential_stealer: 42, other_stealer: 5,  general_leak: 11 },
      resolved:   { vip: 0, domain_stealer: 0, potential_stealer: 42, other_stealer: 5,  general_leak: 11 },
      unresolved: { vip: 0, domain_stealer: 0, potential_stealer: 0,  other_stealer: 0,  general_leak: 0  },
      enumeration: 0,
    },
    n_vulns: {
      total:   { critical: 0, high: 0, medium: 5, low: 13, info: 0 },
      active:  { critical: 0, high: 0, medium: 3, low: 8,  info: 0 },
      passive: { critical: 0, high: 0, medium: 2, low: 5,  info: 0 },
    },
    waf: { count: 2, assets: ["www.securefinance.eu", "app.securefinance.eu"] },
    cdn: { count: 1, assets: ["cdn.securefinance.eu"] },
    unique_ipv4: 3,
    unique_ipv6: 2,
  },

  // ── globaltechcorp.com — scan storico (1 mese fa) ─────────
  {
    idsummary: "sum_001_prev",
    status: "success",
    domain_name: "globaltechcorp.com",
    risk_score: 88,
    creation_date: "2024-02-10T09:15:00Z",
    last_edit: "2024-02-10T09:22:00Z",
    summary_text:
      "Il dominio globaltechcorp.com presentava un rischio complessivo CRITICO. Oltre ai problemi rilevati nel mese successivo, erano presenti 5 CVE critiche attive e nessun WAF attivo.",
    summary_text_en:
      "The domain globaltechcorp.com presented a CRITICAL overall risk. In addition to issues found the following month, 5 critical active CVEs were present and no WAF was active.",
    servizi_esposti_score: 91,
    dataleak_score: 88,
    rapporto_leak_email_score: 80,
    spoofing_score: 95,
    open_ports_score: 85,
    blacklist_score: 60,
    vulnerability_score_active: 97,
    vulnerability_score_passive: 72,
    certificate_score: 65,
    n_port: { "80": { n: 8 }, "443": { n: 9 }, "22": { n: 5 }, "8080": { n: 4 }, "3306": { n: 3 }, "5432": { n: 2 }, "27017": { n: 1 } },
    n_cert_attivi: 3,
    n_cert_scaduti: 4,
    n_asset: 22,
    n_similar_domains: 15,
    email_security: {
      spoofable: "Spoofing possible.",
      dmarc_policy: "none",
      blacklist_detections: 8,
      blacklist_total_list: 60,
      blacklist_detected_list: ["spamhaus", "surbl", "uribl", "barracuda", "sorbs"],
    },
    n_dataleak: {
      total:      { vip: 2, domain_stealer: 9, potential_stealer: 520, other_stealer: 45, general_leak: 88 },
      resolved:   { vip: 0, domain_stealer: 1, potential_stealer: 80,  other_stealer: 5,  general_leak: 10 },
      unresolved: { vip: 2, domain_stealer: 8, potential_stealer: 440, other_stealer: 40, general_leak: 78 },
      enumeration: 14,
    },
    n_vulns: {
      total:   { critical: 5, high: 22, medium: 41, low: 38, info: 0 },
      active:  { critical: 5, high: 16, medium: 28, low: 38, info: 0 },
      passive: { critical: 0, high: 6,  medium: 13, low: 18, info: 0 },
    },
    waf: { count: 0, assets: [] },
    cdn: { count: 1, assets: ["cdn.globaltechcorp.com"] },
    unique_ipv4: 12,
    unique_ipv6: 4,
  },

  // ── globaltechcorp.com — scan storico (2 mesi fa) ─────────
  {
    idsummary: "sum_001_oldest",
    status: "success",
    domain_name: "globaltechcorp.com",
    risk_score: 93,
    creation_date: "2024-01-12T09:15:00Z",
    last_edit: "2024-01-12T09:22:00Z",
    summary_text:
      "Stato iniziale del dominio globaltechcorp.com: rischio CRITICO elevato, nessuna misura di sicurezza perimetrale.",
    summary_text_en:
      "Initial state of globaltechcorp.com: elevated CRITICAL risk, no perimeter security measures in place.",
    servizi_esposti_score: 95,
    dataleak_score: 92,
    rapporto_leak_email_score: 88,
    spoofing_score: 97,
    open_ports_score: 90,
    blacklist_score: 75,
    vulnerability_score_active: 99,
    vulnerability_score_passive: 80,
    certificate_score: 78,
    n_port: { "80": { n: 10 }, "443": { n: 9 }, "22": { n: 7 }, "8080": { n: 6 }, "3306": { n: 4 }, "5432": { n: 3 }, "27017": { n: 2 }, "6379": { n: 1 } },
    n_cert_attivi: 2,
    n_cert_scaduti: 6,
    n_asset: 28,
    n_similar_domains: 18,
    email_security: {
      spoofable: "Spoofing possible.",
      dmarc_policy: "none",
      blacklist_detections: 12,
      blacklist_total_list: 60,
      blacklist_detected_list: ["spamhaus", "surbl", "uribl", "barracuda", "sorbs", "spamcop"],
    },
    n_dataleak: {
      total:      { vip: 5, domain_stealer: 14, potential_stealer: 720, other_stealer: 68, general_leak: 122 },
      resolved:   { vip: 0, domain_stealer: 0,  potential_stealer: 0,   other_stealer: 0,  general_leak: 0   },
      unresolved: { vip: 5, domain_stealer: 14, potential_stealer: 720, other_stealer: 68, general_leak: 122 },
      enumeration: 22,
    },
    n_vulns: {
      total:   { critical: 9, high: 31, medium: 52, low: 45, info: 0 },
      active:  { critical: 9, high: 22, medium: 35, low: 45, info: 0 },
      passive: { critical: 0, high: 9,  medium: 17, low: 22, info: 0 },
    },
    waf: { count: 0, assets: [] },
    cdn: { count: 0, assets: [] },
    unique_ipv4: 16,
    unique_ipv6: 5,
  },
]
